[[redirects]]
  from = "http://appautopass.com.br/*"
  to = "https://appautopass.com.br/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.appautopass.com.br/*"
  to = "https://appautopass.com.br/:splat"
  status = 301
  force = true
